### PR TITLE
Java modularisation

### PR DESCRIPTION
**Pull request by matteodri**

### CODE REVIEW

**Comment by alessandrodalbello** [comment]
Builds are failing here. I imagine you tested it locally and was working fine. Is there any change need to be made in CircleCI pipelines as well?

**Comment by matteodri** [comment]
So, there is one build to compile the library with java 11 and one with Java 8. Why do we want this?
If ti compiles with Java 8 it should also compile with Java 11. 
With my modification the code is compiled with Java 8, except module-info.java which is compiled with Java 9, which is the first version that supports modularisation. 
@volkodavs should we just have one job in Circleci that compiles the library using the default versions set in pom.xml (8 and 9) or do you still want to be able to compile with 11?

**Comment by matteodri** [comment]
I need to play with the pom file, it should be feasible. I need to prevent the second compilation pass for versions above 8.
So the intention is to provide both versions to the public, for a given module, one jar compiled with Java 8 and one jar compiled with Java 11, correct?

**Comment by matteodri** [comment]
I've updated the pull request with another change to the POM.
@volkodavs now by default will use `maven.compiler.source=11 maven.compiler.target=11`,
the build pipeline for java 8 should specify `-P maven-compiler-target-8` on the maven command to activate the profile for Java 8 compilation.

**Comment by alessandrodalbello** [comment]
@volkodavs can you enable the profile Matteo defined in the Java 8 pipeline?

Also, considering the command of Java 11 pipeline is
```bash
mvn clean verify -Dmaven.compiler.source=11 -Dmaven.compiler.target=11
```
shouldn't the command of Java 8 pipeline be
```
mvn clean verify -P maven-compiler-target-8 -Dmaven.compiler.source=11 -Dmaven.compiler.target=8
```
and not just
```
mvn clean verify -P maven-compiler-target-8
```
?

**Pull request merged**
